# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ff9f8507375db872a52d77cc8410d4f67af29ac6a9623dcf6d7038cbac777fdeeac5c256f73410642caa90bf85313a156c3ef6092e553d9eaa5fb37db6bb5059

test:
  secret_key_base: 8cc399f0c98acafcc114e5835a305503b433cb420b1fd174f1b6506fd5dea013420de3abefd25124f951ce46b3b04acfe0f49dbbbc8a9e36038ac8e1d9f5d434

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
